### ISSUE TITLE
您博客的RSS(atom.xml)没有正确生成。

### ISSUE THREAD

**Issue by yzqzss** [nojsja/blogs-hexo#20]
从`_config.yml`来看，是有开启`RSS`的，但目前访问 https://nojsja.github.io/blogs/atom.xml 会得到 404 。
![_config.yml](https://user-images.githubusercontent.com/23720620/145131268-d09bf8cb-1586-4fc5-b2cf-97f6f8e99fe3.png)

ref:https://github.com/saveweb/doing/issues/155

**Comment by nojsja** [comment]
之前已经修改了
